
const dataType = {
    tracking_code: 'string',
    shipping_invoice_number: 'string',
    shipment_currency: 'string',
    total_shipment_cost: 'number',
    tax_charges: 'number',
    fuel_charges: 'number',
    other_costs: 'number',
    shipping_cost: 'number',
    surcharge_cost: 'number',
    insurance_cost: 'number',
    status: 'string',
};

const columnTranslation = {
    '1': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'HAWB #', file: 'HAWB #' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Currency Code', file: 'Currency Code' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Total', file: 'Total' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Tax Amount', file: 'Tax Amount' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Fuel Charge', file: 'Fuel Charge' },
        other_costs:{ table: 'ShipmentCosts', type: 'column', main: 'Other Charges', file: 'Other Charges' },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Valuation Charge', file: 'Valuation Charge' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '2': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'HAWB #', file: 'HAWB #' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Currency Code', file: 'Currency Code' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Total', file: 'Total' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Tax Amount', file: 'Tax Amount' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Fuel Charge', file: 'Fuel Charge' },
        other_costs:{ table: 'ShipmentCosts', type: 'column', main: 'Other Charges', file: 'Other Charges' },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Valuation Charge', file: 'Valuation Charge' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '3': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Column Q', file: 'Air Waybill Number' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Column I', file: 'Bill to Currency' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BN', file: 'Air Waybill Total Amount' },
        tax_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        fuel_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BT', file: 'Column BT Air Waybill Charge Amount' },
        other_costs:{ table: 'ShipmentCosts', type: 'column', main: 'Column BR', file: 'Column BR Air Waybill Charge Amount' },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BP', file: 'Column BP Air Waybill Charge Amount' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BV', file: 'Column BV Air Waybill Charge Amount' },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '4': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Column Q', file: 'Air Waybill Number' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Column I', file: 'Bill to Currency' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BN', file: 'Air Waybill Total Amount' },
        tax_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        fuel_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BT', file: 'Column BT Air Waybill Charge Amount' },
        other_costs:{ table: 'ShipmentCosts', type: 'column', main: 'Column BR', file: 'Column BR Air Waybill Charge Amount' },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BP', file: 'Column BP Air Waybill Charge Amount' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BV', file: 'Column BV Air Waybill Charge Amount' },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '5': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Consignment No', file: 'Consignment No' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: 'AUD (put in hardcoded)', file: 'AUD' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Total Amount', file: 'Total Amount' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'GST', file: 'GST' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Freight Amount', file: 'Freight Amount' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Surcharge', file: 'Surcharge' },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '6': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Consignment No', file: 'Consignment No' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: 'AUD (put in hardcoded)', file: 'AUD' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Total Amount', file: 'Total Amount' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'GST', file: 'GST' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Freight Amount', file: 'Freight Amount' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Surcharge', file: 'Surcharge' },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '7': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Hawb', file: 'Hawb' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: 'EUR (put in hardcoded)', file: 'EUR' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Amount', file: 'Amount' },
        tax_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '8': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Pakketnr', file: 'Pakketnr' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: 'EUR (put in hardcoded)', file: 'EUR' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Pakketbedrag (remove the Euro symbol)', file: 'Pakketbedrag' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '9': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'HAWB #', file: 'HAWB #' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Currency Code', file: 'Currency Code' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Total', file: 'Total' },
        tax_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'column', main: 'Weight Charge', file: 'Weight Charge' },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Valuation Charge', file: 'Valuation Charge' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '10': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Column Q', file: 'Air Waybill Number' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Column I', file: 'Bill to Currency' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BN', file: 'Air Waybill Total Amount' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BX', file: 'Column BX Air Waybill Charge Amount' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BT', file: 'Column BT Air Waybill Charge Amount' },
        other_costs:{ table: 'ShipmentCosts', type: 'column', main: 'Column BR', file: 'Column BR Air Waybill Charge Amount' },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BP', file: 'Column BP Air Waybill Charge Amount' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BV', file: 'Column BV Air Waybill Charge Amount' },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '11': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Column Q', file: 'Air Waybill Number' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Column I', file: 'Bill to Currency' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BN', file: 'Air Waybill Total Amount' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BX', file: 'Column BX Air Waybill Charge Amount' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BT', file: 'Column BT Air Waybill Charge Amount' },
        other_costs:{ table: 'ShipmentCosts', type: 'column', main: 'Column BR', file: 'Column BR Air Waybill Charge Amount' },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BP', file: 'Column BP Air Waybill Charge Amount' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BV', file: 'Column BV Air Waybill Charge Amount' },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '12': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'TrackingNumber', file: 'TrackingNumber' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: 'HKD (put in hardcoded)', file: 'HKD' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'TotalCharge', file: 'TotalCharge' },
        tax_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'column', main: 'INSURANCE CHARGE', file: 'INSURANCE CHARGE' },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '13': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'HAWB No', file: 'HAWB No' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Document Currency', file: 'Document Currency' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Row Total', file: 'Row Total' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Total Tax', file: 'Total Tax' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '14': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'HAWB No', file: 'HAWB No' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Document Currency', file: 'Document Currency' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Row Total', file: 'Row Total' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Total Tax', file: 'Total Tax' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '15': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'HAWB # (Column D)', file: '' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        tax_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '16': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'HAWB # (Column D)', file: '' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        tax_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '17': {
        tracking_code:{ table: 'Shipments', type: 'column', main: '-', file: '-' },
        shipping_invoice_number:{ table: 'Shipments', type: 'column', main: 'Our Invoice No. (Column C)', file: 'Our Invoice No.' },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: 'INR (put in hardcoded)', file: 'INR' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Total Amount (Column P)', file: 'Total Amount' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Total Tax (Column N)', file: 'Total Tax' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '18': {
        tracking_code:{ table: 'Shipments', type: 'column', main: '?', file: '' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        tax_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '19': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'TrackingNo', file: 'TrackingNo' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: 'INR (put in hardcoded)', file: 'INR' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'AMOUNT DUE', file: 'AMOUNT DUE' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'GST', file: 'GST' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'TOTAL', file: 'TOTAL' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '20': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'TrackingNo', file: 'TrackingNo' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: 'INR (put in hardcoded)', file: 'INR' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'AMOUNT DUE', file: 'AMOUNT DUE' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'GST', file: 'GST' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'TOTAL', file: 'TOTAL' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '21': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Column Q', file: 'Luchtvrachtbriefnummer' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Column I', file: 'In rekening gebrachte valuta' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BN', file: 'Totale bedrag luchtvrachtbrief' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BX', file: 'Column BX Totale kosten luchtvrachtbrief' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BT', file: 'Column BT Totale kosten luchtvrachtbrief' },
        other_costs:{ table: 'ShipmentCosts', type: 'column', main: 'Column BR', file: 'Column BR Totale kosten luchtvrachtbrief' },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BP', file: 'Column BP Totale kosten luchtvrachtbrief' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BV', file: 'Column BV Totale kosten luchtvrachtbrief' },
        insurance_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BZ', file: 'Column BZ Totale kosten luchtvrachtbrief' },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '22': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Column Q', file: 'Luchtvrachtbriefnummer' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Column I', file: 'In rekening gebrachte valuta' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BN', file: 'Totale bedrag luchtvrachtbrief' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BX', file: 'Column BX Totale kosten luchtvrachtbrief' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BT', file: 'Column BT Totale kosten luchtvrachtbrief' },
        other_costs:{ table: 'ShipmentCosts', type: 'column', main: 'Column BR', file: 'Column BR Totale kosten luchtvrachtbrief' },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BP', file: 'Column BP Totale kosten luchtvrachtbrief' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BV', file: 'Column BV Totale kosten luchtvrachtbrief' },
        insurance_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BZ', file: 'Column BZ Totale kosten luchtvrachtbrief' },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '23': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Column Q', file: 'Air Waybill Number' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Column I', file: 'In rekening gebrachte valuta' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BN', file: 'Totale bedrag luchtvrachtbrief' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BX', file: 'Column BX Totale kosten luchtvrachtbrief' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BT', file: 'Column BT Totale kosten luchtvrachtbrief' },
        other_costs:{ table: 'ShipmentCosts', type: 'column', main: 'Column BR', file: 'Column BR Totale kosten luchtvrachtbrief' },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BP', file: 'Column BP Totale kosten luchtvrachtbrief' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BV', file: 'Column BV Totale kosten luchtvrachtbrief' },
        insurance_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BZ', file: 'Column BZ Totale kosten luchtvrachtbrief' },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '24': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Column Q', file: 'Air Waybill Number' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Column I', file: 'In rekening gebrachte valuta' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BN', file: 'Totale bedrag luchtvrachtbrief' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BX', file: 'Column BX Totale kosten luchtvrachtbrief' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BT', file: 'Column BT Totale kosten luchtvrachtbrief' },
        other_costs:{ table: 'ShipmentCosts', type: 'column', main: 'Column BR', file: 'Column BR Totale kosten luchtvrachtbrief' },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BP', file: 'Column BP Totale kosten luchtvrachtbrief' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BV', file: 'Column BV Totale kosten luchtvrachtbrief' },
        insurance_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BZ', file: 'Column BZ Totale kosten luchtvrachtbrief' },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '25': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Tracking Number', file: 'Tracking Number' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: 'GBP (put in hardcoded)', file: 'GBP' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Net Amount Due (remove the Pound symbol)', file: 'Net Amount Due' },
        tax_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '26': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Tracking Number', file: 'Tracking Number' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: 'GBP (put in hardcoded)', file: 'GBP' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Net Amount Due (remove the Pound symbol)', file: 'Net Amount Due' },
        tax_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '27': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'HAWB #', file: 'HAWB #' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Currency Code', file: 'Currency Code' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Total', file: 'Total' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Tax Amount', file: 'Tax Amount' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Fuel Charge', file: 'Fuel Charge' },
        other_costs:{ table: 'ShipmentCosts', type: 'column', main: 'Other Charges', file: 'Other Charges' },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Valuation Charge', file: 'Valuation Charge' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Weight Charge', file: 'Weight Charge' },
        insurance_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Base Charge', file: 'Base Charge' },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '28': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'HAWB #', file: 'HAWB #' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Currency Code', file: 'Currency Code' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Total', file: 'Total' },
        tax_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Tax Amount', file: 'Tax Amount' },
        fuel_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Fuel Charge', file: 'Fuel Charge' },
        other_costs:{ table: 'ShipmentCosts', type: 'column', main: 'Other Charges', file: 'Other Charges' },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Valuation Charge', file: 'Valuation Charge' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Weight Charge', file: 'Weight Charge' },
        insurance_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Base Charge', file: 'Base Charge' },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '29': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Column J', file: 'Express or Ground Tracking ID' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: 'USD (put in hardcoded)', file: 'USD' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column F', file: 'Original Amount Due' },
        tax_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '30': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Column J', file: 'Express or Ground Tracking ID' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'value', main: 'USD (put in hardcoded)', file: 'USD' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column F', file: 'Original Amount Due' },
        tax_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        fuel_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        other_costs:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        shipping_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
    '31': {
        tracking_code:{ table: 'Shipments', type: 'column', main: 'Column Q', file: 'Air Waybill Number' },
        shipping_invoice_number:{ table: 'Shipments', type: 'value', main: null, file: null },
        shipment_currency:{ table: 'ShipmentCosts', type: 'column', main: 'Column I', file: 'Bill to Currency' },
        total_shipment_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BN', file: 'Air Waybill Total Amount' },
        tax_charges:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        fuel_charges:{ table: 'ShipmentCosts', type: 'column', main: 'Column BT', file: 'Column BT Air Waybill Charge Amount' },
        other_costs:{ table: 'ShipmentCosts', type: 'column', main: 'Column BR', file: 'Column BR Air Waybill Charge Amount' },
        shipping_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BP', file: 'Column BP Air Waybill Charge Amount' },
        surcharge_cost:{ table: 'ShipmentCosts', type: 'column', main: 'Column BV', file: 'Column BV Air Waybill Charge Amount' },
        insurance_cost:{ table: 'ShipmentCosts', type: 'value', main: null, file: null },
        status:{ table: 'ShipmentCosts', type: 'value', main: 'CLOSED', file: 'CLOSED' },
    },
}

module.exports = {
    dataType,
    columnTranslation,
}